### ISSUE TITLE
Remove feedback form from interface

### ISSUE THREAD

**Issue by allisonnorman** [CBHSQ/findtreatment#560]
As SAMHSA will not have access to remove the Google feedback form after 11/30, we should remove the form from the FindTreatment.gov and findtreatment.samhsa.gov interfaces until another solution to solicit feedback from visitors is set up. 

**FindTreatment.gov**
- [x] Remove link from footer
- [x] Remove beta banner entirely (which includes link)

**findtreatment.samhsa.gov**
- [x] Remove from samhsa.gov interfaces (@BrooklynHopkins - I think you have a list of where these are on the various pages)

**Comment by allisonnorman** [comment]
@Jkrzy - I can make the footer change myself but think there's likely more to the beta banner than I realize. Would you prefer to make both changes or have me make the footer change?

**Comment by Jkrzy** [comment]
@allisonnorman You can make the footer change, and happy to pair on the banner if you'd like!
